== Snort 3.0 Demo

This test suite contains examples of Snort 3.0 usage. Each directory
contains all the files sufficient to demonstrate a use case and a
README that explains the interesting bits.

Demos are executed using bats, a simple bash test framework, which
you can find here: https://github.com/bats-core/bats-core.

To execute the tests:

  ./run_test.sh

run_test.sh will find and expecute "test.bats" files recursively from the
specified [path/to/tests] if provided, or recursively from the current
directory, if no path is provided. Output is in TAPS format with a summary at
the end.

You can also execute a one or more tests from an alternate directory tree by
specifying an alternate path as the first argument file, e.g.:

  ./run_test.sh tests/ips_actions/replace_rewrite

  or (path to the test.bats file)

  ./run_test.sh tests/ips_actions/replace_rewrite/test.bats

  or (some out of tree path to an externally defined test suite)

  ./run_test.sh /some/other/path/tests/

Dockerfiles outlining how to build Snort3 for a specific platform are included
in the Dockerfiles folder.
