This file explains how to analyze performance for open source Snort 3.0
relative to Snort 2.9 in readback mode.  Snort 2 and Snort 3 have some
significant differences but the various configs provide for equivalent
functionality.  For perf testing, these configs should be preferred over using
snort2lua.

* IPS mode

* Disables small segments / 129:12 since maccdc has lots

* Comments out reputation since config is not operational without white/black
  lists

* Comments out perf_monitor since with 3.0 it skews counts

Refer to the following sections for details:

* Scripts
* Confs
* Rules
* Pcaps
* Build
* Testing
* Tips


= Scripts:

{2.9,3.0}/setup.sh - edit to set build, rules, pcaps, and ODP path.

{2.9,3.0}/repeat.sh - processes given conf N times.

{2.9,3.0}/perf_test.sh - driver for running all pcaps against all confs.

{2.9,3.0}/validate.sh - takes same args as repeat.sh to validate setup

The scripts currently support running Snort 3 with multiple packet threads but
only a single Snort 2 instance.  We will provide a means to run multiple Snort
2 processes for a better multi-thread comparison.


= Confs:

decode.{conf,lua} - just decode packets.  No inspectors or rules.

stream.{conf,lua} - adds stream only to decode conf.  No non-stream inspectors.
No rules.

inspect.{conf,lua} - full configuration w/o rules.

detect-min.{conf,lua} - adds rules to snort.conf.

detect-max.{conf,lua} - same as min except with unlimited http flow depths.


= Rules:

Download the appropriate rule sets from snort.org and select an appropriate set
for your tests.


= Pcaps:

Use pcaps containing the traffic needed for your tests.  A general purpose
mixed traffic pcap from your local network is a good starting point.  You can
also find some useful pcaps online or generate them as explained below.

maccdc.pcap = maccdc2012_00000.pcap mostly has a TCP scan in it (SYN-RST).
https://download.netresec.com/pcap/maccdc-2012/maccdc2012_00000.pcap.gz

The tcp_* and udp_* pcaps can be used to generate standard data sheet perf test
pcaps.  Use with abcip like this:

$ common/tcp_1000.sh 4096 | abcip --pcap get250.pcap

# (abcip is here:  https://github.com/crc181/abcip.git)

You should put your pcaps on a ramdisk for the most consistent results.  4G is a good size for the ramdisk.  Generally, pcaps between 1G and 4G will give good results.


= Build:

== Snort 2.9:

$ export CFLAGS="-O3"
$ export PKG_CONFIG_PATH=/path/to/luajit.pc/

$ ./configure --enable-inline-init-failopen --enable-control-socket --enable-side-channel --enable-sourcefire --enable-file-inspect --enable-open-appid --enable-option-checking=fatal --prefix /home/snorty/snort/snort-2.9.12/o3


== Snort 3.0:

$ export CFLAGS="-O3"
$ export CXXFLAGS="-O3 -fno-rtti"
$ configure_cmake.sh --enable-shell --enable-tsc-clock --enable-tcmalloc


= Testing:

== Snort 2:

1.  Setup:

Export the following (or directly set in perf/*/setup.sh):

$ export SNORT2_BUILD=<Snort 2 build prefix>
$ export SNORT2_MIN_RULES=<Snort 2 rules file for min detect>
$ export SNORT2_MAX_RULES=<Snort 2 rules file for max detect>
$ export SNORT_PCAPS=<path to dir containing pcaps for test>
$ export SNORT_ODP=<path to dir containing odp/>

2.  Run perf_test.sh <cpu_mask> <#iterations>

$ cd 2.9
$ ./perf_test.sh 0x1 3

== Snort 3:

1.  Setup:

Same as for Snort 2 except use SNORT3_* instead of SNORT2_*.

You must also edit 3.0/common.lua to set the Snort 3 CPU pinning config.

2.  Run perf_test.sh <mpse> <#iterations> <#threads>

<mpse> ::= hyperscan | ac_full | ac_bnfa | etc.

$ cd 3.0
$ ./perf_test.sh hyperscan 3 1


= Tips

Performance testing can be a tricky affair.  Comparing Snort 2 and Snort 3 is
even more challenging.  Here are some things to consider:

1.  Use the supplied configurations as a starting point to get a baseline.  If
you need to make changes for your deployment, make sure they have an equivalent
impact on Snort 2 and Snort 3 if you are comparing them.

2.  Start with the supplied pcaps.  When you switch to live traffic, it gets
more complicated:

a.  Disable LRO and other NIC accelerations (eg with ethtool).  For IDS mode,
Snort will hadle overlaps the same way the receiving host does.  For IPS mode,
Snort will normalize the TCP stream.

b.  Check your MTU and set Snort's snaplen accordingly.  Otherwise Snort may
not get complete packets.

c.  Check Snort's shutdown stats for things like checksum errors and
normalizations.  High counts likely indicate a problem and you may need to
disable checksums, etc.

d.  Snort does much better with bidirectional traffic.  If you have asymmetric
routing, try to deploy Snort where it will see both directions.  Unidirectional
traffic can not be properly analyzed in general.  Consider an HTTP HEAD
request.  The response headers may indicate a content-length but no body will
follow causing Snort to treat subsequent headers as body.

e.  By default, Snort factors in the address_space_id from the DAQ and VLAN
tags in the packet when hashing flows.  If these are not the same in each
direction, set these variables as appropriate:

    packets.address_space_agnostic
    packets.vlan_agnostic

3.  When comparing Snort 2 and Snort 3, note that Snort 2 may have appeared to
be doing something it wasn't.  Snort 3 counts paint a more accurate picture.

4.  Have a look at these documents:

a.  For general tuning tips: "Using Perfmon and Performance Profiling to Tune
Snort Preprocessors and Rules" available at https://snort.org/documents:

https://snort-org-site.s3.amazonaws.com/production/document_files/files/000/000/030/original/WhitePaper_Snort_PerformanceTuning_2009.pdf

b.  For more information on offloads etc:

https://snort-org-site.s3.amazonaws.com/production/document_files/files/000/000/067/original/packet-offloading-issues.pdf
https://lwn.net/Articles/358910/
https://www.kernel.org/doc/Documentation/networking/segmentation-offloads.txt

